services:
  postgres:
    image: postgres:15-alpine
    container_name: momesso-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: momesso_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: momesso-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: momesso_db
      JWT_SECRET: momesso-super-secret-jwt-key-2024
      JWT_EXPIRES_IN: 7d
      PORT: 3000
      NODE_ENV: production
      FRONTEND_URL: http://localhost:4200
    ports:
      - '3000:3000'

  seed:
    build:
      context: ./backend
      dockerfile: Dockerfile.seed
    container_name: momesso-seed
    depends_on:
      backend:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: momesso_db
    # Roda uma única vez e para — não reinicia
    restart: 'no'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: momesso-frontend
    depends_on:
      - backend
    ports:
      - '4200:80'

volumes:
  postgres_data:
